### ISSUE TITLE
Project ready for evaluation

### ISSUE THREAD

**Issue by SpaceGold** [SpaceGold/apple_mobility_data#3]
@naupaka @melt6457 @mhaliz, thanks for your patience! Master is up to date with a stable build of the Rmd. Working on parameterizing now in the parameterize-rmd branch. Thanks again.

**Comment by SpaceGold** [comment]
Hey guys, in the version above, I forgot to generate my own figure at the end of the Rmd file. I've been working on that tonight. It's really exciting but I've hit a block and could really use some help, please! As of this comment, my WIP is in [the Debugging branch](https://github.com/SpaceGold/apple_mobility_data/commit/c0b272b001ee463adab9dff24e2b1e7ff9cd26fa). I'll check in tomorrow. 

Steps to reproduce: Knit Analysis.Rmd, view Analysis.html. Actual result: forced NA error instead of graphs in Analysis.html. Expected result: a rudimentary graph in Analysis.html.

Relevant facts: I'm clearly struggling with filtering by date in dplyr, plus I haven't gotten to the part where I figure out how to average a month's data down into 7 weekday points per graph.

Thanks!

**Comment by naupaka** [comment]
@SpaceGold you need to add Kory and Michali to your repo as collaborators.

**Comment by SpaceGold** [comment]
@naupaka Hmm, I invited them under Manage Access a number of weeks ago and it says pending invite: 
 
![access](https://user-images.githubusercontent.com/29960822/96359058-04cad180-10c3-11eb-8c57-89414f3414bd.PNG)

**Comment by naupaka** [comment]
I will remind them to accept. Maybe the invite expired?

**Comment by melt6457** [comment]
We must have missed it. The invite definitelt expired. Can you resend?

**Comment by naupaka** [comment]
OK I think things are set up for reviews properly. I'll review this work (the previous assignment) on master, and @melt6457 is in charge of reviewing your PR.

**Comment by naupaka** [comment]
I need to go through and check before we close the issue...

**Comment by naupaka** [comment]
ok all good ✅
